#!/usr/bin/env python3
"""Measure repository structure without parsing a particular programming language.

The report is an advisory sensor. It describes the tree and growth signals; it does
not decide that files should move and it never changes the inspected repository.
Exit status is 0 for a report, 2 for an invalid root or policy.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Sequence


SCHEMA_VERSION = 1
DEFAULT_THRESHOLDS = {
    "observe_direct_production_files": 8,
    "review_direct_production_files": 12,
    "compare_direct_production_files": 20,
}

ALWAYS_IGNORED_DIR_NAMES = {".git", ".hg", ".svn"}
DEFAULT_IGNORED_DIR_NAMES = {
    ".venv",
    "venv",
    "__pycache__",
    ".cache",
    "build",
    "dist",
    "out",
    "target",
    "node_modules",
}

VENDOR_DIR_NAMES = {
    "external",
    "node_modules",
    "third-party",
    "third_party",
    "vendor",
    "vendors",
}
GENERATED_DIR_NAMES = {
    "generated",
    "generate",
    "gen",
    "autogen",
    "autogenerated",
    "__generated__",
}
TEST_DIR_NAMES = {
    "test",
    "tests",
    "spec",
    "specs",
    "fixture",
    "fixtures",
    "__tests__",
}
DOC_DIR_NAMES = {"doc", "docs", "documentation"}
BUILD_OUTPUT_DIR_NAMES = {"build", "dist", "out", "target"}
TOOL_DIR_NAMES = {
    ".buildkite",
    ".circleci",
    ".github",
    "agent",
    "agents",
    "bin",
    "ci",
    "hack",
    "hacks",
    "script",
    "scripts",
    "tool",
    "tools",
}
DOC_EXTENSIONS = {".adoc", ".markdown", ".md", ".mdown", ".rst", ".txt"}
METADATA_NAMES = {
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
    "authors",
    "build",
    "build.bazel",
    "copying",
    "dockerfile",
    "kbuild",
    "kconfig",
    "license",
    "makefile",
    "notice",
    "owners",
    "readme",
    "readme.md",
}
BOUNDARY_MARKER_NAMES = {
    "agents.md",
    "build",
    "build.bazel",
    "cargo.toml",
    "codeowners",
    "go.mod",
    "kbuild",
    "kconfig",
    "makefile",
    "maintainers",
    "owners",
    "package.xml",
    "pom.xml",
    "pyproject.toml",
    "readme.md",
}
ROLE_NAMES = {
    "production",
    "test",
    "generated",
    "vendor",
    "documentation",
    "tooling",
    "build_output",
    "other",
}


class InventoryError(ValueError):
    """Raised when the inventory request cannot be evaluated safely."""


@dataclass(frozen=True)
class Policy:
    thresholds: dict[str, int]
    exclude: tuple[str, ...]
    role_overrides: tuple[tuple[str, str], ...]
    boundary_paths: tuple[str, ...]
    exclude_defaults: bool = True


@dataclass(frozen=True)
class FileRecord:
    path: str
    role: str
    lines: int | None


def _normalise_relative(path: Path) -> str:
    return PurePosixPath(*path.parts).as_posix()


def _matches(path: str, patterns: Iterable[str]) -> bool:
    pure = PurePosixPath(path)
    return any(
        fnmatch.fnmatchcase(path, pattern)
        or fnmatch.fnmatchcase(path, pattern.rstrip("/"))
        or pure.match(pattern)
        for pattern in patterns
    )


def _validate_thresholds(raw: Any) -> dict[str, int]:
    thresholds = dict(DEFAULT_THRESHOLDS)
    if raw is None:
        return thresholds
    if not isinstance(raw, dict):
        raise InventoryError("policy thresholds must be an object")
    for key, value in raw.items():
        if key not in DEFAULT_THRESHOLDS:
            raise InventoryError(f"unsupported threshold {key!r}")
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise InventoryError(f"threshold {key!r} must be a non-negative integer")
        thresholds[key] = value
    ordered = [
        thresholds["observe_direct_production_files"],
        thresholds["review_direct_production_files"],
        thresholds["compare_direct_production_files"],
    ]
    if ordered != sorted(ordered):
        raise InventoryError("thresholds must be ordered observe <= review <= compare")
    return thresholds


def _validate_patterns(raw: Any, field: str) -> tuple[str, ...]:
    if raw is None:
        return ()
    if not isinstance(raw, list) or not all(isinstance(item, str) and item for item in raw):
        raise InventoryError(f"policy {field} must be a list of non-empty strings")
    return tuple(raw)


def _validate_bool(raw: Any, field: str, default: bool) -> bool:
    if raw is None:
        return default
    if not isinstance(raw, bool):
        raise InventoryError(f"policy {field} must be a boolean")
    return raw


def _validate_role_overrides(raw: Any) -> tuple[tuple[str, str], ...]:
    if raw is None:
        return ()
    if not isinstance(raw, dict):
        raise InventoryError("policy role_overrides must be an object")
    result: list[tuple[str, str]] = []
    for pattern, role in raw.items():
        if not isinstance(pattern, str) or not pattern:
            raise InventoryError("role_overrides patterns must be non-empty strings")
        if role not in ROLE_NAMES:
            raise InventoryError(f"unsupported file role {role!r}")
        result.append((pattern, role))
    return tuple(result)


def load_policy(path: Path | None) -> Policy:
    if path is None:
        return Policy(DEFAULT_THRESHOLDS.copy(), (), (), (), True)
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError) as exc:
        raise InventoryError(f"cannot read policy {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise InventoryError(f"policy {path} is not valid JSON: {exc}") from exc
    if not isinstance(raw, dict):
        raise InventoryError("policy root must be an object")
    version = raw.get("version", 1)
    if version != 1:
        raise InventoryError(f"unsupported policy version {version!r}")
    return Policy(
        thresholds=_validate_thresholds(raw.get("thresholds")),
        exclude=_validate_patterns(raw.get("exclude"), "exclude"),
        role_overrides=_validate_role_overrides(raw.get("role_overrides")),
        boundary_paths=_validate_patterns(raw.get("boundary_paths"), "boundary_paths"),
        exclude_defaults=_validate_bool(raw.get("exclude_defaults"), "exclude_defaults", True),
    )


def _role_for(path: str, name: str, policy: Policy) -> str:
    for pattern, role in policy.role_overrides:
        if _matches(path, (pattern,)):
            return role

    parts = set(PurePosixPath(path).parts[:-1])
    lower_name = name.lower()
    lower_path = path.lower()
    if parts & VENDOR_DIR_NAMES:
        return "vendor"
    if parts & GENERATED_DIR_NAMES or any(
        marker in lower_name for marker in (".generated.", ".gen.", ".autogen.")
    ):
        return "generated"
    if parts & TEST_DIR_NAMES or lower_name.endswith((".test", ".spec")):
        return "test"
    if parts & DOC_DIR_NAMES:
        return "documentation"
    if lower_name == "readme.md" or Path(name).suffix.lower() in DOC_EXTENSIONS:
        return "documentation"
    if parts & TOOL_DIR_NAMES:
        return "tooling"
    if parts & BUILD_OUTPUT_DIR_NAMES:
        return "build_output"
    if lower_name in METADATA_NAMES or lower_path.endswith(("/build", "/makefile")):
        return "other"
    return "production"


def _count_text_lines(path: Path) -> int | None:
    """Count physical lines while treating files with NUL bytes as binary."""
    try:
        with path.open("rb") as handle:
            first = handle.read(8192)
            if b"\0" in first:
                return None
            count = first.count(b"\n")
            saw_bytes = bool(first)
            last_byte = first[-1:] if first else b""
            while chunk := handle.read(1024 * 1024):
                saw_bytes = True
                count += chunk.count(b"\n")
                last_byte = chunk[-1:]
    except OSError:
        return None
    if saw_bytes and last_byte != b"\n":
        count += 1
    return count


def _git_paths(root: Path) -> set[str] | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-co", "--exclude-standard", "--"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return {
        _normalise_relative(Path(line))
        for line in result.stdout.splitlines()
        if line.strip()
    }


def _path_in_scope(relative: str, include: tuple[str, ...], exclude: tuple[str, ...]) -> bool:
    if _matches(relative, exclude):
        return False
    return not include or _matches(relative, include)


def _disposition(production_files: int, thresholds: dict[str, int]) -> str:
    if production_files >= thresholds["compare_direct_production_files"]:
        return "compare-candidates"
    if production_files >= thresholds["review_direct_production_files"]:
        return "review"
    if production_files >= thresholds["observe_direct_production_files"]:
        return "observe"
    return "retain"


def _direct_readme(records: list[FileRecord]) -> str | None:
    for record in records:
        if Path(record.path).name.lower() == "readme.md":
            return record.path
    return None


def _markers(records: list[FileRecord]) -> list[str]:
    return sorted(
        {
            Path(record.path).name
            for record in records
            if Path(record.path).name.lower() in BOUNDARY_MARKER_NAMES
        },
        key=str.lower,
    )


def _directory_depth(path: str) -> int:
    return 0 if path == "." else len(PurePosixPath(path).parts)


def _recursive_stats(
    directory_paths: set[str], records_by_directory: dict[str, list[FileRecord]]
) -> dict[str, dict[str, Any]]:
    """Aggregate direct records bottom-up instead of scanning every descendant per directory."""
    stats: dict[str, dict[str, Any]] = {}
    for directory in directory_paths:
        records = records_by_directory.get(directory, [])
        roles: dict[str, int] = {}
        for record in records:
            roles[record.role] = roles.get(record.role, 0) + 1
        stats[directory] = {
            "files": len(records),
            "physical_lines": sum(record.lines or 0 for record in records),
            "production_lines": sum(
                record.lines or 0 for record in records if record.role == "production"
            ),
            "roles": roles,
        }

    for directory in sorted(directory_paths, key=_directory_depth, reverse=True):
        if directory == ".":
            continue
        parent = _normalise_relative(Path(directory).parent) or "."
        child = stats[directory]
        parent_stats = stats.setdefault(
            parent, {"files": 0, "physical_lines": 0, "production_lines": 0, "roles": {}}
        )
        parent_stats["files"] += child["files"]
        parent_stats["physical_lines"] += child["physical_lines"]
        parent_stats["production_lines"] += child["production_lines"]
        for role, count in child["roles"].items():
            parent_stats["roles"][role] = parent_stats["roles"].get(role, 0) + count
    return stats


def inventory(
    root: Path,
    policy: Policy | None = None,
    include: Sequence[str] = (),
    exclude: Sequence[str] = (),
    tracked: bool = False,
    use_default_excludes: bool | None = None,
    count_lines: bool = True,
) -> dict[str, Any]:
    root = root.resolve()
    if not root.exists():
        raise InventoryError(f"root does not exist: {root}")
    if not root.is_dir():
        raise InventoryError(f"root is not a directory: {root}")
    policy = policy or Policy(DEFAULT_THRESHOLDS.copy(), (), (), (), True)
    if use_default_excludes is None:
        use_default_excludes = policy.exclude_defaults
    include_patterns = tuple(include)
    exclude_patterns = tuple(policy.exclude) + tuple(exclude)
    tracked_paths: set[str] | None = None
    path_source = "filesystem"
    if tracked:
        tracked_paths = _git_paths(root)
        if tracked_paths is None:
            raise InventoryError("--tracked requires a Git repository and an available git command")
        path_source = "git"

    records_by_directory: dict[str, list[FileRecord]] = {}
    directory_paths: set[str] = {"."}
    excluded_paths = 0
    scanned_files = 0

    for current, dirnames, filenames in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        current_rel = _normalise_relative(current_path.relative_to(root)) or "."
        directory_paths.add(current_rel)

        kept_dirs: list[str] = []
        for dirname in sorted(dirnames):
            child = current_path / dirname
            child_rel = _normalise_relative(child.relative_to(root))
            default_excluded = use_default_excludes and dirname in DEFAULT_IGNORED_DIR_NAMES
            if (
                child.is_symlink()
                or dirname in ALWAYS_IGNORED_DIR_NAMES
                or default_excluded
                or _matches(child_rel, exclude_patterns)
            ):
                excluded_paths += 1
                continue
            kept_dirs.append(dirname)
            directory_paths.add(child_rel)
        dirnames[:] = kept_dirs

        records: list[FileRecord] = []
        for filename in sorted(filenames):
            path = current_path / filename
            if path.is_symlink() or not path.is_file():
                excluded_paths += 1
                continue
            relative = _normalise_relative(path.relative_to(root))
            if tracked_paths is not None and relative not in tracked_paths:
                continue
            if not _path_in_scope(relative, include_patterns, exclude_patterns):
                excluded_paths += 1
                continue
            role = _role_for(relative, filename, policy)
            record = FileRecord(
                relative,
                role,
                _count_text_lines(path) if count_lines else None,
            )
            records.append(record)
            scanned_files += 1
        if records:
            records_by_directory[current_rel] = records

    children_by_directory: dict[str, int] = {path: 0 for path in directory_paths}
    for path in directory_paths:
        if path == ".":
            continue
        parent = _normalise_relative(Path(path).parent) or "."
        children_by_directory[parent] = children_by_directory.get(parent, 0) + 1

    recursive_stats = _recursive_stats(directory_paths, records_by_directory)
    directory_rows: list[dict[str, Any]] = []
    for directory in sorted(directory_paths, key=lambda value: (value != ".", value)):
        direct_records = records_by_directory.get(directory, [])
        role_counts: dict[str, int] = {}
        for record in direct_records:
            role_counts[record.role] = role_counts.get(record.role, 0) + 1
        aggregate = recursive_stats[directory]
        direct_production = role_counts.get("production", 0)
        row = {
            "path": directory,
            "depth": _directory_depth(directory),
            "direct_files": len(direct_records),
            "direct_production_files": direct_production,
            "recursive_files": aggregate["files"],
            "physical_lines": aggregate["physical_lines"],
            "production_lines": aggregate["production_lines"],
            "child_directories": children_by_directory.get(directory, 0),
            "roles": dict(sorted(role_counts.items())),
            "recursive_roles": dict(sorted(aggregate["roles"].items())),
            "readme": _direct_readme(direct_records),
            "markers": _markers(direct_records),
            "boundary_candidate": _matches(directory, policy.boundary_paths),
            "disposition": _disposition(direct_production, policy.thresholds),
        }
        directory_rows.append(row)

    role_totals: dict[str, int] = {}
    for records in records_by_directory.values():
        for record in records:
            role_totals[record.role] = role_totals.get(record.role, 0) + 1
    return {
        "schema_version": SCHEMA_VERSION,
        "root": str(root),
        "path_source": path_source,
        "thresholds": policy.thresholds,
        "filters": {
            "include": list(include_patterns),
            "exclude": list(exclude_patterns),
            "default_excludes": bool(use_default_excludes),
        },
        "summary": {
            "files_scanned": scanned_files,
            "directories_scanned": len(directory_paths),
            "excluded_paths": excluded_paths,
            "line_count_mode": "physical" if count_lines else "skipped",
            "roles": dict(sorted(role_totals.items())),
        },
        "directories": directory_rows,
    }


def _format_text(report: dict[str, Any]) -> str:
    lines = [
        f"Structure inventory: {report['root']}",
        f"Path source: {report['path_source']}",
        "Thresholds: "
        + ", ".join(
            f"{key}={value}" for key, value in report["thresholds"].items()
        ),
        "",
    ]
    for row in report["directories"]:
        readme = "yes" if row["readme"] else "no"
        boundary = " boundary-candidate" if row["boundary_candidate"] else ""
        lines.append(
            f"{row['path']}: direct={row['direct_files']} "
            f"production={row['direct_production_files']} "
            f"recursive={row['recursive_files']} "
            f"lines={row['production_lines']} "
            f"depth={row['depth']} children={row['child_directories']} "
            f"readme={readme} disposition={row['disposition']}{boundary}"
        )
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path, help="repository or source root to inspect")
    parser.add_argument("--policy", type=Path, help="optional JSON structure policy")
    parser.add_argument("--include", action="append", default=[], help="path glob to include")
    parser.add_argument("--exclude", action="append", default=[], help="path glob to exclude")
    parser.add_argument(
        "--tracked",
        action="store_true",
        help="inventory Git tracked and untracked non-ignored files instead of the filesystem",
    )
    parser.add_argument(
        "--no-default-excludes",
        action="store_true",
        help="include conventional cache, dependency, and build directories (VCS metadata stays excluded)",
    )
    parser.add_argument(
        "--skip-line-count",
        action="store_true",
        help="skip reading file contents when only path and role metrics are needed",
    )
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args(argv)
    try:
        policy = load_policy(args.policy)
        report = inventory(
            args.root,
            policy=policy,
            include=args.include,
            exclude=args.exclude,
            tracked=args.tracked,
            use_default_excludes=not args.no_default_excludes,
            count_lines=not args.skip_line_count,
        )
    except InventoryError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.format == "json":
        print(json.dumps(report, ensure_ascii=True, indent=2, sort_keys=True))
    else:
        print(_format_text(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
